language: objective-c
osx_image: xcode8.2

xcode_project: PPAsyncDrawingKit.xcodeproj
xcode_scheme: PPAsyncDrawingKit-Demo

notifications:
  webhooks: https://hook.bearychat.com/=bw9Wn/travis/f3e6508fc6b306599bc7b7be711e77fc