language: objective-c
osx_image: xcode8.3

install: true
branches:
  only:
    - swift

xcode_workspace: AsyncDrawingKit.xcworkspace

jobs:
  include:
    - xcode_scheme: AsyncDrawingKit
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
    - stage: carthage
      script:
        - carthage build --cache-builds --no-skip-current --platform iOS
        
notifications:
  webhooks: https://hook.bearychat.com/=bw9Wn/travis/f3e6508fc6b306599bc7b7be711e77fc